### PR TITLE
Call close_logger whenever a module is terminated

### LINKED ISSUE #6: close_logger() is not called if an RVIC process is halted before reaching the 'final' step
[close_logger()](https://github.com/pacificclimate/rvic-daccs/blob/master/rvic/core/log.py#L90) is a function that reverts `stdout`, `stderr` and the logging method back to default. However, it is only called in the final steps of each process, and the function will never be called if a process is halted due to unexpected reasons. Fix the processes to ensure the function is called whenever a process is terminated.

### PR DESCRIPTION
**Pull request by sum1lim**
resolve #6 

Main functions of convert(), parameters(), and convolution() are wrapped with a`try-except` block, and `close_logger()` is called for every exceptions under `BaseException`.

### CODE REVIEW

**Review by nikola-rados — COMMENTED** [review]
Functionally, I think this works great. That being said I think we may want to be a bit more careful with out usage of `try/except`. The `try` block encapsulates a bunch of different things that may not necessarily related or cause an error at all. From what I recall, we want to implement this to avoid the app crashing when bad inputs are given. Is that specific to a method (answer may vary between modules)? If it is, we may only want to wrap that method in `try/except`. If the entire file has the potential to cause a problem then I _think_ we can leave it as you have it.

**Comment by sum1lim** [comment]
> From what I recall, we want to implement this to avoid the app crashing when bad inputs are given.

@nikola-rados From my experience, there are more cases to consider than just the cases of bad inputs. As I mentioned before, multiple submissions of `osprey` processes at the same time causes a crash (I don't remember why type of error though). I believe it is something that is complicated to be handled by catching the parts where the errors are being thrown, while simply wrapping the main functions with a try-except block would handle such cases.

My intention in this PR is to ascertain that the software calls the `close_logger` function "whenever" it is terminated, and that includes the cases of any unexpected errors.

**Comment by nikola-rados** [comment]
That is a fair way to go about it. 

To make it more palatable perhaps you could try wrapping the modules into a function (within the same module) and run the `try/except` over that function rather than many lines of code. It may not be ideal for this set of files so if you are happy with it we can move on.

**Comment by sum1lim** [comment]
@nikola-rados I replaced the `try-except` with `try-finally` block to call `close_call` on any occasion.

**Review by nikola-rados — APPROVED** [review]
LGTM, we should release a new package with your fixes :+1:

**Pull request merged**
